// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var Block       = require("bs-platform/lib/js/block.js");
var Glamor      = require("bs-glamor/src/glamor.js");
var $$String    = require("bs-platform/lib/js/string.js");
var Pervasives  = require("bs-platform/lib/js/pervasives.js");
var Caml_format = require("bs-platform/lib/js/caml_format.js");

function calculateFontSize(size) {
  var s = Pervasives.string_of_float(Caml_format.caml_float_of_string($$String.sub(size, 0, size.length - 2 | 0)) * 0.06);
  return $$String.sub(s, 0, s.length - 1 | 0);
}

function createContainer(url, size) {
  return Glamor.css(/* :: */[
              Glamor.transition("opacity 800ms ease-in-out"),
              /* :: */[
                Glamor.backgroundImage("url(" + url + ")"),
                /* :: */[
                  Glamor.position("relative"),
                  /* :: */[
                    Glamor.backgroundSize("cover"),
                    /* :: */[
                      Glamor.fontSize(calculateFontSize(size)),
                      /* [] */0
                    ]
                  ]
                ]
              ]
            ]);
}

function createSize(size) {
  return Glamor.css(/* :: */[
              Glamor.height(size),
              /* :: */[
                Glamor.width(size),
                /* [] */0
              ]
            ]);
}

var hide = Glamor.css(/* :: */[
      Glamor.opacity("0"),
      /* [] */0
    ]);

var show = Glamor.css(/* :: */[
      Glamor.opacity("1"),
      /* [] */0
    ]);

var title = Glamor.css(/* :: */[
      Glamor.fontSize("1.5em"),
      /* :: */[
        Glamor.lineHeight("1.5em"),
        /* [] */0
      ]
    ]);

var details = Glamor.css(/* :: */[
      Glamor.lineHeight("1.5em"),
      /* :: */[
        Glamor.textShadow("0 0 10px rgba(0,0,0,.7)"),
        /* :: */[
          Glamor.position("absolute"),
          /* :: */[
            Glamor.bottom("1.25em"),
            /* :: */[
              Glamor.left("1.25em"),
              /* :: */[
                Glamor.right("1.25em"),
                /* :: */[
                  Glamor.margin("0"),
                  /* :: */[
                    Glamor.color("#fff"),
                    /* :: */[
                      Glamor.fontFamily("Arial, Helvetica, sans-serif"),
                      /* :: */[
                        Glamor.textDecoration("none"),
                        /* :: */[
                          Glamor.zIndex("1"),
                          /* [] */0
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var link = Glamor.css(/* :: */[
      Glamor.color("#fff"),
      /* :: */[
        Glamor.textDecoration("none"),
        /* :: */[
          /* Selector */Block.__(1, [
              "&:hover",
              /* :: */[
                Glamor.textDecoration("underline"),
                /* [] */0
              ]
            ]),
          /* [] */0
        ]
      ]
    ]);

var gradient = Glamor.css(/* :: */[
      /* Selector */Block.__(1, [
          "&:after",
          /* :: */[
            Glamor.backgroundImage("linear-gradient(180deg,transparent 0,rgba(0,0,0,.35) 70%,rgba(0,0,0,.7))"),
            /* :: */[
              Glamor.content("\"\""),
              /* :: */[
                Glamor.position("absolute"),
                /* :: */[
                  Glamor.width("100%"),
                  /* :: */[
                    Glamor.height("100%"),
                    /* :: */[
                      Glamor.top("0"),
                      /* :: */[
                        Glamor.left("0"),
                        /* [] */0
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]),
      /* [] */0
    ]);

var Css = /* module */[
  /* createContainer */createContainer,
  /* createSize */createSize,
  /* hide */hide,
  /* show */show,
  /* title */title,
  /* details */details,
  /* link */link,
  /* gradient */gradient
];

exports.calculateFontSize = calculateFontSize;
exports.Css               = Css;
/* hide Not a pure module */
